/**
 * useAutoTitle — no-op
 *
 * Conversation titles are generated by the backend and delivered
 * as a `title` SSE event at the end of the first message stream.
 * The frontend receives it via apiStreamChat's onTitle callback
 * and updates the sidebar via onRenameSession in useSessionChat.
 *
 * No client-side title generation is performed.
 */
export function useAutoTitle() {}
