/**
 * exportConversation.js
 * ──────────────────────
 * Exports the full conversation as a clean Markdown file.
 * Includes: title, date, all messages, sources with page refs.
 *
 * Why Markdown (not PDF)?
 *   Markdown is universally readable, searchable, pasteable.
 *   Browser-generated PDFs have unpredictable layout across devices.
 *   Users can open .md in Notion, Obsidian, VS Code, GitHub — anywhere.
 *   If they want PDF they can print-to-PDF from any Markdown viewer.
 *
 * Backend provision (when connected):
 *   Could also call POST /api/conversations/{id}/export
 *   Backend returns a pre-formatted file with server-rendered content.
 *   For now: entirely client-side from IDB — no network needed.
 */

/**
 * Build the markdown string from a conversation.
 *
 * @param {object}   conversation  — { id, title, createdAt }
 * @param {object[]} messages      — Message[]
 * @param {object[]} documents     — Document[]
 * @returns {string} markdown content
 */
export function buildMarkdown(conversation, messages, documents) {
  const lines = []
  const date  = new Date(conversation.createdAt).toLocaleDateString(undefined, {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  // ── Header ────────────────────────────────────────────────────────
  lines.push(`# ${conversation.title}`)
  lines.push(``)
  lines.push(`**Exported from Docognix** · ${date}`)
  lines.push(``)

  // ── Document list ─────────────────────────────────────────────────
  if (documents.length > 0) {
    lines.push(`## Documents`)
    lines.push(``)
    documents.forEach((doc, i) => {
      const pages = doc.totalPages ? ` · ${doc.totalPages} page${doc.totalPages !== 1 ? 's' : ''}` : ''
      lines.push(`${i + 1}. **${doc.filename}**${pages}`)
    })
    lines.push(``)
  }

  // ── Conversation ──────────────────────────────────────────────────
  lines.push(`## Conversation`)
  lines.push(``)

  const chatMessages = messages.filter(m => !m.streaming)

  for (const msg of chatMessages) {
    if (msg.role === 'user') {
      lines.push(`### You`)
      lines.push(``)
      lines.push(msg.content)
      lines.push(``)
    } else if (msg.role === 'assistant') {
      lines.push(`### Docognix`)
      lines.push(``)
      lines.push(msg.content || '_No response_')
      lines.push(``)

      // Sources
      const meta = msg.metadata
      if (meta?.sources?.length > 0) {
        lines.push(`**Sources**`)
        lines.push(``)
        meta.sources.forEach(src => {
          const conf = src.confidence ? ` · ${src.confidence}% confidence` : ''
          lines.push(`- ${src.filename}, Page ${src.page}${conf}`)
          if (src.snippet) lines.push(`  > "${src.snippet}"`)
        })
        lines.push(``)
      }

      // Contradiction
      if (meta?.state === 'contradiction' && meta?.contradiction?.detected) {
        const c = meta.contradiction
        lines.push(`> ⚠️ **Contradiction detected** — ${c.topic ?? 'conflicting information'}`)
        if (c.sides?.length === 2) {
          lines.push(`>`)
          lines.push(`> | View A | View B |`)
          lines.push(`> |--------|--------|`)
          lines.push(`> | ${c.sides[0].filename} p.${c.sides[0].page}: "${c.sides[0].stance}" | ${c.sides[1].filename} p.${c.sides[1].page}: "${c.sides[1].stance}" |`)
          if (c.explanation) lines.push(`>`)
          if (c.explanation) lines.push(`> *${c.explanation}*`)
        }
        lines.push(``)
      }

      // Answer state badge
      if (meta?.state && meta.state !== 'contradiction') {
        const stateLabel = {
          supported:    '✅ Answer supported by documents',
          partial:      '⚠️ Answer partially supported',
          not_relevant: '❌ No relevant information found',
        }[meta.state]
        if (stateLabel) lines.push(`*${stateLabel}*`)
        if (meta.latencyMs) lines.push(`*${meta.latencyMs}ms · ${meta.chunksUsed ?? 0} chunks used*`)
        lines.push(``)
      }
    }
  }

  // ── Footer ────────────────────────────────────────────────────────
  lines.push(`---`)
  lines.push(`*Generated by [Docognix](https://docognix.app) — RAG-powered document intelligence*`)

  return lines.join('\n')
}

/**
 * Trigger a browser file download with the given content.
 *
 * @param {string} filename
 * @param {string} content
 * @param {string} mimeType
 */
export function downloadFile(filename, content, mimeType = 'text/markdown;charset=utf-8') {
  const blob = new Blob([content], { type: mimeType })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename
  a.style.display = 'none'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * One-call export: build markdown and trigger download.
 *
 * @param {object}   conversation
 * @param {object[]} messages
 * @param {object[]} documents
 */
export function exportConversation(conversation, messages, documents) {
  const md       = buildMarkdown(conversation, messages, documents)
  const safeName = (conversation.title ?? 'conversation')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60)
  downloadFile(`docognix-${safeName}.md`, md)
}
