/**
 * identity.js
 * ───────────
 * Single source of truth for who the current user is.
 *
 * anonymous_id rules:
 *   - Generated by the BACKEND (UUID4), not the frontend.
 *   - Returned on first POST /api/v1/documents/upload response.
 *   - Stored permanently in localStorage after first upload.
 *   - Empty string "" means not yet assigned (first-time user, no upload yet).
 *
 * user_id:
 *   - null until login (future auth).
 *
 * Keys:
 *   docognix_anonymous_id  — UUID from backend
 *   docognix_user          — set after login, null until then
 */

const ANON_KEY = 'docognix_anonymous_id'
const USER_KEY = 'docognix_user'

/**
 * Get stored anonymous_id.
 * Returns "" (empty string) if not yet set — caller handles first-time case.
 * Never generates an ID locally — that is the backend's responsibility.
 */
export function getAnonymousId() {
  return localStorage.getItem(ANON_KEY) ?? ''
}

/**
 * Store anonymous_id returned by backend.
 * Called after first upload response, never called otherwise.
 */
export function setAnonymousId(id) {
  if (id && id !== localStorage.getItem(ANON_KEY)) {
    localStorage.setItem(ANON_KEY, id)
  }
}

/** Returns logged-in user object or null. */
export function getUser() {
  try { return JSON.parse(localStorage.getItem(USER_KEY)) ?? null }
  catch { return null }
}

/**
 * Returns the current identity.
 * Before first upload: { anonymousId: "", userId: null, isLoggedIn: false }
 * After first upload:  { anonymousId: "uuid", userId: null, isLoggedIn: false }
 * After login:         { anonymousId: "uuid", userId: "uuid", isLoggedIn: true }
 */
export function getCurrentIdentity() {
  const user = getUser()
  return {
    anonymousId: getAnonymousId(),
    userId:      user?.id ?? null,
    isLoggedIn:  !!user?.id,
  }
}

/** Called after successful login/signup. */
export function setUser(user) {
  localStorage.setItem(USER_KEY, JSON.stringify(user))
}

/** Called after logout. anonymous_id intentionally kept. */
export function clearUser() {
  localStorage.removeItem(USER_KEY)
}
